module.exports = {
    // Environment
    WIND_VARIANCE_STEPS: 7,
    WIND_VARIANCE_INCREMENT: 2,
    WIND_POWER: 0.01,

    GRAVITY: .24,

    // Shooting
    WIND_BREAKER_SHELL_POWER: 1.06,
    SHELL_MAX_SHOT_SPEED: 1366/50,
    SHELL_AIR_DRAG: .0005,
    SHELL_DAMAGE_DIRECT: 50,
    SHELL_DAMAGE_GROUND: 40,
    SHELL_DAMAGE_GROUND_AOE: 40,

    TANK_COLLISION_RADIUS: 19,

    WALL_HEIGHT_MIN: 70,
    WALL_HEIGHT_MAX: 260,
    WALL_WIDTH: 24,
    WALL_WIND_DAMPENING: [0,0,0,0,0,10,30,60],

    // Clouds
    CLOUD_SPEED: 1,
    CLOUD_MAX: 4,
    CLOUD_SPAWN_MIN: 6,
    CLOUD_SPAWN_MAX: 18,


    // GRAPHICS
    GROUND_HEIGHT: 60,
};